[package]
name = "burn_book"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "~0.18", features = [
    "std",
    "tui",
    "train",
    "vision",
    "wgpu",
    "fusion",
], default-features = false }

mnist_dataset = { git = "https://github.com/daniel-j-anderson-dev/mnist_dataset.git", features = [
    "burn",
] }
